import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const root = new URL("../../", import.meta.url);
const html = await readFile(new URL("www/mdvwb/index.html", root), "utf8");
const css = await readFile(new URL("www/mdvwb/styles.css", root), "utf8");
const placement = await readFile(new URL("www/mdvwb/dashboard-placement-editor.js", root), "utf8");
const dashboardEditor = await readFile(new URL("www/mdvwb/dashboard-editor.js", root), "utf8");

assert.match(html, /class="admin-topbar"/);
assert.doesNotMatch(html, /class="page-header"/);
assert.doesNotMatch(html, /class="summary"/);
assert.doesNotMatch(html, /class="manager-panel"/);
assert.doesNotMatch(html, /class="configuration-panel"/);
assert.match(html, /id="dashboardGridInput"/);
assert.doesNotMatch(html, /id="dashboardGridButton"/);
assert.doesNotMatch(html, /id="dashboardScaleDownButton"|id="dashboardScaleResetButton"|id="dashboardScaleUpButton"/);
assert.doesNotMatch(html, /dashboardMarkerRotation|Поворот:/);
assert.match(html, /id="dashboardMarkerX"[^>]*step="1"/);
assert.match(html, /id="dashboardMarkerY"[^>]*step="1"/);
assert.match(placement, /data-device-key/);
assert.match(placement, /data-bus-id/);
assert.match(placement, /configuredBuses/);
assert.match(placement, /setBusVisible/);
assert.match(placement, /setDeviceVisible/);
assert.match(placement, /snapCoordinate/);
assert.match(placement, /dashboard\.fans\.filter\(\(fan\) => fan\.visible\)/);
assert.match(placement, /fan-marker-number/);
assert.doesNotMatch(placement, /const FAN_ICON/);
assert.match(css, /dashboard-grid-enabled::after/);
assert.match(css, /background-size: 1% 100%, 100% 1%, 5% 100%, 100% 5%/);
assert.match(css, /\.dashboard-editor-workspace \.fan-marker[\s\S]*width: 52px/);
assert.match(css, /\.dashboard-editor-workspace \.fan-marker-number[\s\S]*font-size: 1\.08rem/);
assert.doesNotMatch(html, /Шины берутся из общей конфигурации/);
assert.match(html, /id="dashboardGlobalMarkerScale"/);
assert.doesNotMatch(html, /id="dashboardMarkerScale"/);
assert.match(placement, /device-catalog-item-selected/);
assert.match(placement, /startClientX/);
assert.match(placement, /deltaX \/ this\.drag\.canvasWidth/);
assert.doesNotMatch(placement, /updateSelectedFromPointer/);
assert.match(dashboardEditor, /setMarkerScale/);
assert.match(dashboardEditor, /previewViewport\.addEventListener\("wheel"/);
assert.match(dashboardEditor, /setPreviewScale/);
assert.doesNotMatch(placement, /rotationInput|marker-rotation/);
assert.match(dashboardEditor, /applyUniformMarkerScale/);
assert.match(css, /\.buses-compact-page \.bus-grid\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);
assert.match(css, /\.device-catalog-item-selected/);

assert.match(html, /id="dashboardPanelSelect"/);
assert.match(html, /id="dashboardNewPanelButton"/);
assert.match(html, /id="dashboardPanelIdInput"/);
assert.match(html, /id="dashboardDefaultPanelInput"/);
assert.match(html, /id="dashboardDuplicatePanelButton"/);
assert.match(html, /id="dashboardDeletePanelButton"/);
assert.match(html, /id="dashboardPanelUrlPreview"/);
assert.match(html, /id="backgroundFileInput"[\s\S]*id="dashboardSettingsDrawer"|id="dashboardSettingsDrawer"[\s\S]*id="backgroundFileInput"/);
assert.doesNotMatch(html, /id="dashboardBackgroundButton"/);
assert.doesNotMatch(html, /id="dashboardBackgroundDrawer"/);
assert.match(dashboardEditor, /normalizeDashboardCollection/);
assert.match(dashboardEditor, /panelId:\s*this\.state\.selectedPanelId/);
assert.match(dashboardEditor, /createPanel\(\)/);
assert.match(dashboardEditor, /duplicatePanel\(\)/);
assert.match(dashboardEditor, /deletePanel\(\)/);
assert.match(css, /\.dashboard-panel-switcher/);

console.log("MDVWB compact admin editor static tests: OK");
