#!/bin/sh
set -eu

usage()
{
    cat <<'USAGE'
Usage: modbus-hardware-readonly-check.sh --bus N [options]

Options:
  --config PATH              Managed bus environment file.
                             Default: /etc/default/mdvwb-N
  --output DIRECTORY         Evidence directory.
                             Default: ./mdvwb-modbus-readonly-bus-N-UTC
  --discovery-timeout SEC    Maximum discovery wait. Default: 90
  --capture-seconds SEC      MQTT state capture duration. Default: 30
  --help                     Show this help.

The check performs only the profile-defined read-only discovery probe and normal
runtime polling. It never publishes a device-control command.
USAGE
}

fail()
{
    printf 'MDVWB_READONLY_ERROR: %s\n' "$*" >&2
    exit 1
}

require_positive_integer()
{
    value=$1
    name=$2
    case "$value" in
        ''|*[!0-9]*) fail "$name must be a positive integer" ;;
    esac
    [ "$value" -gt 0 ] || fail "$name must be a positive integer"
}

command_required()
{
    command -v "$1" >/dev/null 2>&1 || fail "required command is missing: $1"
}

bus=
config=
output=
discovery_timeout=90
capture_seconds=30

while [ "$#" -gt 0 ]; do
    case "$1" in
        --bus)
            [ "$#" -ge 2 ] || fail "--bus requires a value"
            bus=$2
            shift 2
            ;;
        --config)
            [ "$#" -ge 2 ] || fail "--config requires a path"
            config=$2
            shift 2
            ;;
        --output)
            [ "$#" -ge 2 ] || fail "--output requires a directory"
            output=$2
            shift 2
            ;;
        --discovery-timeout)
            [ "$#" -ge 2 ] || fail "--discovery-timeout requires seconds"
            discovery_timeout=$2
            shift 2
            ;;
        --capture-seconds)
            [ "$#" -ge 2 ] || fail "--capture-seconds requires seconds"
            capture_seconds=$2
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            fail "unknown argument: $1"
            ;;
    esac
done

require_positive_integer "$bus" "--bus"
[ "$bus" -le 999 ] || fail "--bus must be in range 1..999"
require_positive_integer "$discovery_timeout" "--discovery-timeout"
require_positive_integer "$capture_seconds" "--capture-seconds"

[ -n "$config" ] || config="/etc/default/mdvwb-$bus"
if [ -z "$output" ]; then
    timestamp=$(date -u +%Y%m%dT%H%M%SZ)
    output="./mdvwb-modbus-readonly-bus-$bus-$timestamp"
fi

command_required mosquitto_pub
command_required mosquitto_sub
command_required systemctl
command_required journalctl
command_required timeout

[ -r "$config" ] || fail "managed bus configuration is not readable: $config"

# The file is generated by mdvwb-manager and has the same trust model as
# deploy/mdvwb-run: root-owned shell assignments only.
# shellcheck disable=SC1090
. "$config"

: "${MDVWB_PROTOCOL:?MDVWB_PROTOCOL is missing in $config}"
[ "$MDVWB_PROTOCOL" = "modbus_rtu" ] ||
    fail "bus $bus uses protocol '$MDVWB_PROTOCOL', expected modbus_rtu"
: "${MDVWB_PORT:?MDVWB_PORT is missing in $config}"
: "${MDVWB_MODBUS_PROFILE:?MDVWB_MODBUS_PROFILE is missing in $config}"
: "${MDVWB_ADDRESSES:?MDVWB_ADDRESSES is missing in $config}"

mqtt_host=${MDVWB_MQTT_HOST:-127.0.0.1}
mqtt_port=${MDVWB_MQTT_PORT:-1883}
mqtt_user=${MDVWB_MQTT_USER:-}
mqtt_password=${MDVWB_MQTT_PASSWORD:-}
service="mdvwb@$bus.service"
manager_service=${MDVWB_MANAGER_SERVICE:-mdvwb-manager.service}
status_topic="/mdvwb/buses/$bus/discovery/status"
result_topic="/mdvwb/buses/$bus/discovery/result"
start_topic="/mdvwb/buses/$bus/discovery/start"

mqtt_publish()
{
    topic=$1
    payload=$2
    set -- mosquitto_pub -h "$mqtt_host" -p "$mqtt_port" -t "$topic" -m "$payload"
    if [ -n "$mqtt_user" ]; then
        set -- "$@" -u "$mqtt_user"
        if [ -n "$mqtt_password" ]; then
            set -- "$@" -P "$mqtt_password"
        fi
    fi
    "$@"
}

mqtt_discovery_subscribe()
{
    set -- mosquitto_sub -h "$mqtt_host" -p "$mqtt_port" -v \
        -t "$status_topic" -t "$result_topic"
    if [ -n "$mqtt_user" ]; then
        set -- "$@" -u "$mqtt_user"
        if [ -n "$mqtt_password" ]; then
            set -- "$@" -P "$mqtt_password"
        fi
    fi
    "$@"
}


stream_has_fresh_result()
{
    awk -v status="$status_topic" -v result="$result_topic" '
        $1 == status && $0 ~ /"state"[[:space:]]*:[[:space:]]*"running"/ {
            running = NR
        }
        running && NR > running && $1 == result {
            fresh = 1
        }
        END { exit fresh ? 0 : 1 }
    ' "$output/discovery.stream.txt"
}

extract_fresh_result()
{
    awk -v status="$status_topic" -v result="$result_topic" '
        $1 == status && $0 ~ /"state"[[:space:]]*:[[:space:]]*"running"/ {
            running = NR
        }
        running && NR > running && $1 == result {
            line = $0
            sub(/^[^ ]+[ ]*/, "", line)
            value = line
        }
        END { print value }
    ' "$output/discovery.stream.txt"
}

topic_has_payload()
{
    topic=$1
    awk -v topic="$topic" '
        $1 == topic && NF >= 2 { found = 1 }
        END { exit found ? 0 : 1 }
    ' "$output/mqtt-state.txt"
}

mkdir -p "$output"
chmod 0700 "$output" 2>/dev/null || true

started_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
cat >"$output/manifest.txt" <<EOF_MANIFEST
schema=1
startedAt=$started_at
bus=$bus
service=$service
config=$(basename "$config")
protocol=$MDVWB_PROTOCOL
port=$MDVWB_PORT
profile=$MDVWB_MODBUS_PROFILE
configuredAddresses=$MDVWB_ADDRESSES
mqttHost=$mqtt_host
mqttPort=$mqtt_port
readOnly=true
powerCommandsPublished=false
EOF_MANIFEST

original_active=0
service_touched=0
subscriber_pid=
cleanup()
{
    if [ -n "${subscriber_pid:-}" ]; then
        kill "$subscriber_pid" 2>/dev/null || true
        wait "$subscriber_pid" 2>/dev/null || true
    fi
    if [ "$service_touched" -eq 1 ]; then
        if [ "$original_active" -eq 1 ]; then
            systemctl start "$service" >/dev/null 2>&1 || true
        else
            systemctl stop "$service" >/dev/null 2>&1 || true
        fi
    fi
}
trap cleanup EXIT HUP INT TERM

if systemctl is-active --quiet "$service"; then
    original_active=1
fi
systemctl is-active "$manager_service" >"$output/manager.status.txt" 2>&1 ||
    fail "$manager_service is not active"
systemctl status "$service" --no-pager >"$output/service.before.txt" 2>&1 || true

: >"$output/discovery.stream.txt"
mqtt_discovery_subscribe >"$output/discovery.stream.txt" 2>"$output/discovery.subscriber.stderr.txt" &
subscriber_pid=$!
sleep 1

# Discovery may stop the selected bus service. Mark it for restoration before
# publishing so every later failure still restores the original service state.
service_touched=1

# This is the only MQTT publication made by the checker. Manager discovery uses
# the reviewed profile's read-only probe and never emits a Modbus write.
mqtt_publish "$start_topic" ""

deadline=$(( $(date +%s) + discovery_timeout ))
while ! stream_has_fresh_result; do
    if ! kill -0 "$subscriber_pid" 2>/dev/null; then
        fail "discovery subscriber exited before a fresh result"
    fi
    [ "$(date +%s)" -lt "$deadline" ] ||
        fail "Modbus discovery did not produce a fresh result within ${discovery_timeout}s"
    sleep 1
done

kill "$subscriber_pid" 2>/dev/null || true
wait "$subscriber_pid" 2>/dev/null || true
subscriber_pid=

extract_fresh_result >"$output/discovery.result.json"
if ! grep -Eq '"success"[[:space:]]*:[[:space:]]*true' \
    "$output/discovery.result.json"; then
    fail "Modbus discovery returned an unsuccessful result"
fi

addresses=$(sed -n \
    's/.*"addresses"[[:space:]]*:[[:space:]]*\[\([^]]*\)\].*/\1/p' \
    "$output/discovery.result.json" | tr -d '[:space:]')
[ -n "$addresses" ] || fail "Modbus discovery found no logical addresses"
printf '%s\n' "$addresses" >"$output/discovered-addresses.txt"
configured_addresses=$(printf '%s' "$MDVWB_ADDRESSES" | tr -d '[:space:]')
if [ "$addresses" != "$configured_addresses" ]; then
    cat >"$output/address-mismatch.txt" <<EOF_MISMATCH
configured=$configured_addresses
discovered=$addresses
Save the reviewed discovery result in the bus configuration and rerun the check.
EOF_MISMATCH
    fail "discovered addresses differ from configured addresses; evidence was preserved"
fi

# Manager discovery deliberately leaves the bus stopped. Start the normal
# runtime only long enough to capture factual retained states, then restore the
# service state that existed before this check.
systemctl start "$service"
runtime_deadline=$(( $(date +%s) + 15 ))
while ! systemctl is-active --quiet "$service"; do
    [ "$(date +%s)" -lt "$runtime_deadline" ] ||
        fail "$service did not become active"
    sleep 1
done

set -- mosquitto_sub -h "$mqtt_host" -p "$mqtt_port" -v \
    -t "/devices/sist-${bus}/#"
old_ifs=$IFS
IFS=,
for address in $addresses; do
    IFS=$old_ifs
    set -- "$@" -t "/devices/Fan-${bus}_${address}/#"
    IFS=,
done
IFS=$old_ifs
if [ -n "$mqtt_user" ]; then
    set -- "$@" -u "$mqtt_user"
    if [ -n "$mqtt_password" ]; then
        set -- "$@" -P "$mqtt_password"
    fi
fi
set +e
timeout "$capture_seconds" "$@" \
    >"$output/mqtt-state.txt" 2>"$output/mqtt-state.stderr.txt"
capture_status=$?
set -e
# GNU timeout normally returns 124. A mock or a broker-side clean exit may
# return zero; both are acceptable because the evidence itself is inspected.
[ "$capture_status" -eq 0 ] || [ "$capture_status" -eq 124 ] ||
    fail "MQTT state capture failed with exit code $capture_status"

systemctl status "$service" --no-pager >"$output/service.after.txt" 2>&1 || true
journalctl -u "$service" --since "$started_at" --no-pager \
    >"$output/journal.txt" 2>&1 || true

poll_topics=0
old_ifs=$IFS
IFS=,
for address in $addresses; do
    IFS=$old_ifs
    case "$address" in
        ''|*[!0-9]*) fail "discovery returned a non-numeric logical address" ;;
    esac
    prefix="/devices/Fan-${bus}_${address}/controls"
    if topic_has_payload "$prefix/Power" &&
       topic_has_payload "$prefix/AlarmCode"; then
        poll_topics=$((poll_topics + 1))
    fi
    IFS=,
done
IFS=$old_ifs

discovered_count=$(awk -F, '{print NF}' "$output/discovered-addresses.txt")
completed_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
cat >"$output/SUMMARY.txt" <<EOF_SUMMARY
MDVWB Modbus read-only hardware evidence
completedAt=$completed_at
bus=$bus
profile=$MDVWB_MODBUS_PROFILE
discoveredAddresses=$addresses
discoveredCount=$discovered_count
addressesWithPowerAndAlarmCode=$poll_topics
readOnly=true
powerCommandsPublished=false
serviceInitiallyActive=$original_active
serviceStateWillBeRestored=true
EOF_SUMMARY

[ "$poll_topics" -eq "$discovered_count" ] ||
    fail "not every discovered address produced Power and AlarmCode state during capture"

printf 'MDVWB Modbus read-only hardware check: OK\n'
printf 'Evidence directory: %s\n' "$output"
